SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK
         INNER JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE YEAR(sales_date) = 2022 and MONTH(sales_date) = 01
GROUP BY CATEGORY
ORDER BY CATEGORY